In [2]:
# 6-19-2026

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_fires = pd.read_csv("../data/fire_events_with_domains.csv")

In [5]:
df_fires.head()

,time,latitude,longitude,gwis_ba_target,domain_id,area,biomes,cams_co2fire,cams_frpfire,drought_code_max,...,swvl1,swvl2,swvl3,swvl4,t2m_max,t2m_mean,t2m_min,tp,vpd,ws10
0,2011-01-01,43.125,132.875,21.503023,4,565025340.0,15.0,NaN,0.0,0.000000,...,0.337228,0.338602,0.339852,0.377954,263.25803,256.87710,252.17323,0.350181,0.612398,2.974318
1,2011-01-01,41.375,121.625,214.948550,47,580685900.0,15.0,NaN,0.0,78.867190,...,0.329196,0.329674,0.342462,0.293115,268.53876,263.51370,258.96646,0.099479,1.840315,3.200563
2,2011-01-01,41.125,121.375,42.986618,47,582878300.0,15.0,NaN,0.0,89.208336,...,0.263521,0.266909,0.277763,0.233878,269.10895,264.72153,260.44240,0.056045,2.115829,3.845847
3,2011-01-01,38.875,60.375,64.448320,16,602096640.0,8.0,NaN,0.0,1642.150000,...,0.013903,0.058413,0.131723,0.163531,281.87384,276.91650,272.45175,0.205564,3.421349,3.884015
4,2011-01-01,37.125,61.125,21.473710,16,616393900.0,8.0,NaN,0.0,1405.640600,...,0.151022,0.108020,0.139074,0.156350,284.79620,278.67374,273.80170,1.654482,3.947975,2.521311

In [6]:
df_fires.shape

(3590844, 44)

In [7]:
df_fires.describe()

,latitude,longitude,gwis_ba_target,domain_id,area,biomes,cams_co2fire,cams_frpfire,drought_code_max,drought_code_mean,...,swvl1,swvl2,swvl3,swvl4,t2m_max,t2m_mean,t2m_min,tp,vpd,ws10
count,3.590844e+06,3.590844e+06,3.590844e+06,3.590844e+06,3.590844e+06,3.539572e+06,1.316751e+06,3.590844e+06,3.580823e+06,3.580823e+06,...,3.533368e+06,3.533368e+06,3.533368e+06,3.533368e+06,3.590844e+06,3.590844e+06,3.590844e+06,3.590844e+06,3.590844e+06,3.590844e+06
mean,3.447690e+00,1.968535e+01,1.165037e+03,1.710681e+01,7.080064e+08,5.652609e+00,4.363315e-02,1.284596e-01,5.396209e+02,5.160905e+02,...,2.154438e-01,2.363981e-01,2.664176e-01,3.034430e-01,3.026833e+02,2.963250e+02,2.906734e+02,8.689953e+00,1.679007e+01,2.668251e+00
std,2.339411e+01,6.057241e+01,3.927165e+03,1.509552e+01,9.356799e+07,4.888990e+00,2.847390e-01,8.049344e-01,3.462835e+02,3.410983e+02,...,1.099126e-01,1.016699e-01,9.384808e-02,1.025053e-01,6.994241e+00,6.684524e+00,6.834045e+00,1.805995e+01,9.320646e+00,9.515803e-01
min,-5.462500e+01,-1.798750e+02,5.708795e-09,-1.000000e+00,2.646683e+08,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-1.598255e-03,-4.005529e-04,-3.541879e-04,-5.551115e-17,2.540700e+02,2.476313e+02,2.387633e+02,-1.332268e-12,0.000000e+00,2.239980e-01
25%,-1.412500e+01,-1.062500e+01,4.554671e+01,4.000000e+00,7.089647e+08,2.000000e+00,4.071090e-03,0.000000e+00,2.897460e+02,2.686562e+02,...,1.298110e-01,1.630563e-01,1.991721e-01,2.248027e-01,3.002095e+02,2.938599e+02,2.877441e+02,4.135663e-03,9.822455e+00,1.951626e+00
50%,-3.125000e+00,2.437500e+01,2.002834e+02,1.100000e+01,7.482218e+08,2.000000e+00,1.168883e-02,0.000000e+00,5.038112e+02,4.813856e+02,...,2.008633e-01,2.284164e-01,2.639091e-01,3.043490e-01,3.040212e+02,2.979147e+02,2.922389e+02,1.070708e+00,1.508464e+01,2.579051e+00
75%,1.312500e+01,3.912500e+01,7.773532e+02,2.700000e+01,7.603473e+08,1.200000e+01,3.326400e-02,5.196762e-02,7.355000e+02,7.101562e+02,...,2.887884e-01,3.061992e-01,3.347103e-01,3.810554e-01,3.070819e+02,3.005299e+02,2.953430e+02,8.831594e+00,2.232571e+01,3.226524e+00
max,7.012500e+01,1.798750e+02,7.638605e+04,4.900000e+01,7.693140e+08,1.500000e+01,1.559702e+02,1.832579e+02,1.000012e+04,1.000000e+04,...,7.486575e-01,7.474247e-01,7.439337e-01,7.587701e-01,3.236490e+02,3.159133e+02,3.083669e+02,9.208061e+02,7.884431e+01,1.444054e+01

In [8]:
df_fires.isna().sum()
# can drop cols that are problematic and won't add much to predictions or encoder space
# biomes (base models will anyways train on a single domain, so likely part of same biome)
# cams_co2fire (two thirds of the values are missing)
# drought_code max and mean (precipitation and temp are the inputs for dc, so it's unnecessary)
# fcci_ba (opting for gwis_ba rather than fcci since fcci is monthly res)
# fwi_max (anyways have mean, and max will be noisy, mean is more stable)
# lai (ndvi does a better job for vegetation load)
# lst_day (anyways have temp)
# sst (anyways have temp)

time                        0
latitude                    0
longitude                   0
gwis_ba_target              0
domain_id                   0
area                        0
biomes                  51272
cams_co2fire          2274093
cams_frpfire                0
drought_code_max        10021
drought_code_mean       10021
ecoregion               50688
fcci_ba                359345
fwi_max                  7045
fwi_mean                 7045
gwis_ba                     0
gwis_ba_valid_mask          0
lai                      9654
lccs_class_1                0
lccs_class_2                0
lccs_class_3                0
lccs_class_4                0
lccs_class_6                0
lccs_class_7                0
lsm                         0
lst_day                123879
ndvi                    70606
pop_dens                14183
pyrome                      0
rel_hum                     0
skt                         0
ssr                         0
ssrd                       12
sst                   3542978
swvl1                   57476
swvl2                   57476
swvl3                   57476
swvl4                   57476
t2m_max                     0
t2m_mean                    0
t2m_min                     0
tp                          0
vpd                         0
ws10                        0
dtype: int64

In [9]:
print(list(df_fires.columns))

['time', 'latitude', 'longitude', 'gwis_ba_target', 'domain_id', 'area', 'biomes', 'cams_co2fire', 'cams_frpfire', 'drought_code_max', 'drought_code_mean', 'ecoregion', 'fcci_ba', 'fwi_max', 'fwi_mean', 'gwis_ba', 'gwis_ba_valid_mask', 'lai', 'lccs_class_1', 'lccs_class_2', 'lccs_class_3', 'lccs_class_4', 'lccs_class_6', 'lccs_class_7', 'lsm', 'lst_day', 'ndvi', 'pop_dens', 'pyrome', 'rel_hum', 'skt', 'ssr', 'ssrd', 'sst', 'swvl1', 'swvl2', 'swvl3', 'swvl4', 't2m_max', 't2m_mean', 't2m_min', 'tp', 'vpd', 'ws10']

In [10]:
columns_to_drop = [
    "biomes",
    "cams_co2fire",
    "drought_code_max",
    "drought_code_mean",
    "fcci_ba",
    "fwi_max",
    "lai",
    "lst_day",
    "sst"
]

df_fires = df_fires.drop(columns=columns_to_drop, errors="ignore") # allow for reruns

In [11]:
df_fires.isna().sum()

time                      0
latitude                  0
longitude                 0
gwis_ba_target            0
domain_id                 0
area                      0
cams_frpfire              0
ecoregion             50688
fwi_mean               7045
gwis_ba                   0
gwis_ba_valid_mask        0
lccs_class_1              0
lccs_class_2              0
lccs_class_3              0
lccs_class_4              0
lccs_class_6              0
lccs_class_7              0
lsm                       0
ndvi                  70606
pop_dens              14183
pyrome                    0
rel_hum                   0
skt                       0
ssr                       0
ssrd                     12
swvl1                 57476
swvl2                 57476
swvl3                 57476
swvl4                 57476
t2m_max                   0
t2m_mean                  0
t2m_min                   0
tp                        0
vpd                       0
ws10                      0
dtype: int64

In [12]:
missing_swvl = df_fires["swvl1"].isna()
df_fires[missing_swvl]["lsm"].value_counts()
df_fires[missing_swvl][["lccs_class_1", "lccs_class_2"]].value_counts().head(10)

lccs_class_1  lccs_class_2
0.000000      0.000000        7052
              0.037037         341
0.432099      28.469135        223
0.000000      0.024691         189
2.641975      16.654322        172
2.308642      1.444444         171
0.000000      9.172839         166
1.753086      14.345679        158
0.432099      3.012346         150
10.148149     17.283950        144
Name: count, dtype: int64

In [13]:
df_fires[missing_swvl]["lsm"].value_counts(normalize=True)

lsm
0.000000    0.091151
0.046710    0.004854
0.322354    0.003880
0.266175    0.003775
0.189655    0.003480
              ...
0.317331    0.000017
0.000014    0.000017
0.253852    0.000017
0.480939    0.000017
0.121153    0.000017
Name: proportion, Length: 3422, dtype: float64

In [14]:
# to deal with all the missing swvl data, will use knn imputation using precip, temp, humidity (strong mositure indicators)

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

In [16]:
scale_cols = ["tp", "t2m_mean", "rel_hum"]
# normalize feature cols
scaler = StandardScaler()
df_fires[scale_cols] = scaler.fit_transform(df_fires[scale_cols])

In [17]:
impute_cols = ["tp", "t2m_mean", "rel_hum", "swvl1", "swvl2", "swvl3", "swvl4"]
# only use a sample for knn to reduce num distance calculations (knn is O(n^2))
complete_mask = df_fires["swvl1"].notna()
sample_pool = df_fires.loc[complete_mask, impute_cols].sample(n=20000, random_state=5)

In [18]:
imputer = KNNImputer(n_neighbors=5, weights="distance")
imputer.fit(sample_pool)

KNNImputer(weights='distance')

In [ ]:
missing_mask = df_fires["swvl1"].isna()
missing_idx = df_fires.loc[missing_mask, impute_cols].index
batch_size = 1000

for start in range(0, len(missing_idx), batch_size):
    batch_idx = missing_idx[start:start + batch_size]
    df_fires.loc[batch_idx, impute_cols] = imputer.transform(df_fires.loc[batch_idx, impute_cols])
    print(f"done {start + batch_size} of {len(missing_idx)}")
# batching because it was taking a while and i couldn't tell how long it would take
# finished 3 min

done 1000 of 57476
done 2000 of 57476
done 3000 of 57476
done 4000 of 57476
done 5000 of 57476
done 6000 of 57476
done 7000 of 57476
done 8000 of 57476
done 9000 of 57476
done 10000 of 57476
done 11000 of 57476
done 12000 of 57476
done 13000 of 57476
done 14000 of 57476
done 15000 of 57476
done 16000 of 57476
done 17000 of 57476
done 18000 of 57476
done 19000 of 57476
done 20000 of 57476
done 21000 of 57476
done 22000 of 57476
done 23000 of 57476
done 24000 of 57476
done 25000 of 57476
done 26000 of 57476
done 27000 of 57476
done 28000 of 57476
done 29000 of 57476
done 30000 of 57476
done 31000 of 57476
done 32000 of 57476
done 33000 of 57476
done 34000 of 57476
done 35000 of 57476
done 36000 of 57476
done 37000 of 57476
done 38000 of 57476
done 39000 of 57476
done 40000 of 57476
done 41000 of 57476
done 42000 of 57476
done 43000 of 57476
done 44000 of 57476
done 45000 of 57476
done 46000 of 57476
done 47000 of 57476
done 48000 of 57476
done 49000 of 57476
done 50000 of 57476
done 51000 of 57476
done 52000 of 57476
done 53000 of 57476
done 54000 of 57476
done 55000 of 57476
done 56000 of 57476
done 57000 of 57476
done 58000 of 57476

In [20]:
df_fires[scale_cols] = scaler.inverse_transform(df_fires[scale_cols]) # undo normalization

In [22]:
df_fires.isna().sum() # values have been imputed for swvl vars, no missings

time                      0
latitude                  0
longitude                 0
gwis_ba_target            0
domain_id                 0
area                      0
cams_frpfire              0
ecoregion             50688
fwi_mean               7045
gwis_ba                   0
gwis_ba_valid_mask        0
lccs_class_1              0
lccs_class_2              0
lccs_class_3              0
lccs_class_4              0
lccs_class_6              0
lccs_class_7              0
lsm                       0
ndvi                  70606
pop_dens              14183
pyrome                    0
rel_hum                   0
skt                       0
ssr                       0
ssrd                     12
swvl1                     0
swvl2                     0
swvl3                     0
swvl4                     0
t2m_max                   0
t2m_mean                  0
t2m_min                   0
tp                        0
vpd                       0
ws10                      0
dtype: int64

In [25]:
df_fires["time"] = pd.to_datetime(df_fires["time"])

In [ ]:
# need to impute for ndvi now. since ndvi doesn't change too much over time, will look at time before/after missing value and interpolate

In [26]:
df_fires.groupby(["latitude", "longitude"])["time"].apply(lambda x: x.diff().value_counts())

latitude  longitude
-54.375   -68.125    8 days       1
-52.625   -69.125    8 days       1
-52.375   -68.875    467 days     1
                     8 days       1
-51.375   -69.875    8 days       1
                                 ..
 70.125    171.375   334 days     1
                     2938 days    1
           171.625   8 days       2
                     334 days     1
                     2930 days    1
Name: time, Length: 869694, dtype: int64

In [28]:
def interpolate_by_time(group):
    group = group.set_index("time")
    group["ndvi"] = group["ndvi"].interpolate(method="time", limit_direction="both", limit=20)
    return group.reset_index()
# set a limit so interpolation doesn't happen over crazy time diffs (over 20 nan rows)

In [29]:
df_fires = df_fires.groupby(["latitude", "longitude"], group_keys=False).apply(interpolate_by_time)

C:\Users\Yash\AppData\Local\Temp\ipykernel_17576\3981338502.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_fires = df_fires.groupby(["latitude", "longitude"], group_keys=False).apply(interpolate_by_time)

In [ ]:
df_fires.isna().sum() # cut ndvi missings over half

time                      0
latitude                  0
longitude                 0
gwis_ba_target            0
domain_id                 0
area                      0
cams_frpfire              0
ecoregion             50688
fwi_mean               7045
gwis_ba                   0
gwis_ba_valid_mask        0
lccs_class_1              0
lccs_class_2              0
lccs_class_3              0
lccs_class_4              0
lccs_class_6              0
lccs_class_7              0
lsm                       0
ndvi                  29262
pop_dens              14183
pyrome                    0
rel_hum                   0
skt                       0
ssr                       0
ssrd                     12
swvl1                     0
swvl2                     0
swvl3                     0
swvl4                     0
t2m_max                   0
t2m_mean                  0
t2m_min                   0
tp                        0
vpd                       0
ws10                      0
dtype: int64

In [34]:
df_fires = df_fires.dropna(subset=["ndvi"]) # simply drop ndvi with long temporal missingness

In [38]:
df_fires = df_fires.dropna(subset=["pop_dens", "ssrd"]) # drop missing pop den since only 14k rows, drop missing ssrp, only 12 rows

In [39]:
df_fires.isna().sum()

time                      0
latitude                  0
longitude                 0
gwis_ba_target            0
domain_id                 0
area                      0
cams_frpfire              0
ecoregion             31783
fwi_mean               3393
gwis_ba                   0
gwis_ba_valid_mask        0
lccs_class_1              0
lccs_class_2              0
lccs_class_3              0
lccs_class_4              0
lccs_class_6              0
lccs_class_7              0
lsm                       0
ndvi                      0
pop_dens                  0
pyrome                    0
rel_hum                   0
skt                       0
ssr                       0
ssrd                      0
swvl1                     0
swvl2                     0
swvl3                     0
swvl4                     0
t2m_max                   0
t2m_mean                  0
t2m_min                   0
tp                        0
vpd                       0
ws10                      0
dtype: int64

In [40]:
df_fires = df_fires.dropna(subset=["fwi_mean"]) # onmly 3k fwi missing, good enough to just drop

In [41]:
df_fires.isna().sum()

time                      0
latitude                  0
longitude                 0
gwis_ba_target            0
domain_id                 0
area                      0
cams_frpfire              0
ecoregion             29071
fwi_mean                  0
gwis_ba                   0
gwis_ba_valid_mask        0
lccs_class_1              0
lccs_class_2              0
lccs_class_3              0
lccs_class_4              0
lccs_class_6              0
lccs_class_7              0
lsm                       0
ndvi                      0
pop_dens                  0
pyrome                    0
rel_hum                   0
skt                       0
ssr                       0
ssrd                      0
swvl1                     0
swvl2                     0
swvl3                     0
swvl4                     0
t2m_max                   0
t2m_mean                  0
t2m_min                   0
tp                        0
vpd                       0
ws10                      0
dtype: int64

In [42]:
df_fires.shape

(3548322, 35)

In [ ]:
3590844-3548322 # only 40k rows were gone

42522

In [ ]:
(3590844-3548322)/3590844*100 # only 1% of rows were removed :)

1.1841784271330082

In [45]:
df_fires.to_csv("fire_cleaned.csv", index=False)

In [ ]:
# summary:

#straight up removed the following cols:
# biomes (base models will anyways train on a single domain, so likely part of same biome)
# cams_co2fire (two thirds of the values are missing)
# drought_code max and mean (precipitation and temp are the inputs for dc, so it's unnecessary)
# fcci_ba (opting for gwis_ba rather than fcci since fcci is monthly res)
# fwi_max (anyways have mean, and max will be noisy, mean is more stable)
# lai (ndvi does a better job for vegetation load)
# lst_day (anyways have temp)
# sst (anyways have temp)

# used knn imputation for swvl variables using temp, precip, and humidity as features
# temporal imputation for ndvi, dropped rows where temporal gaps were too big
# straight up removed rows with missing values for pop den, fwi, and ssrd